### ISSUE TITLE
Permission for Particles Not Working As Expected

### ISSUE THREAD

**Issue by MisterCommand** [MediusEcho/ParticleHats#1]
Hi, thank you for your great plugin!
However, I've found some issues when I am using Mysql and permission.
I used the default particles.yml and added required permission for each effect, the permission can show up in the database too but other players still can access the effects without required permission.
This is the same when I edit current effects in game.
However, the permission system worked when I add new effects in game.
Am I doing anything wrong?
Thanks in advance!

**Comment by MediusEcho** [comment]
The default particles menu included uses the [override](https://github.com/MediusEcho/ParticleHats/wiki/Actions#override) action, which means that effect will not check for permission. 

The new effects you create require permission because they're using the [equip](https://github.com/MediusEcho/ParticleHats/wiki/Actions#equip) action by default. To get the results you are after try editing the particles menu and setting each effects action to `equip`

**Comment by MisterCommand** [comment]
Thanks!
